[project]
name = "kalshi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "quantike", email = "55246750+quantike@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "cryptography>=43.0.3",
    "loguru>=0.7.2",
    "requests>=2.32.3",
    "websockets>=13.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
