services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"  # S3 compatible API
      - "9001:9001"  # Web console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "\
        until mc alias set local http://minio:9000 minio minio123; do \
          echo 'Waiting for MinIO...'; sleep 2; \
        done; \
        mc mb -p local/market-data && \
        mc admin user add local ducklake dlpassword && \
        mc admin policy attach local readwrite --user ducklake && \
        echo 'MinIO bucket \"market-data\" and user \"ducklake\" ready.'"
    restart: "no"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ducklake
      POSTGRES_PASSWORD: ducklake
      POSTGRES_DB: ducklake_catalog
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  minio_data:
  pg_data:
