[project]
name = "pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "quantike", email = "55246750+quantike@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
pipeline = "pipeline:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
